### PR TITLE
support DPO, RM and PPO for ti_to_ti models

### PR DESCRIPTION
**Pull request by htlou**
# Description

Describe your changes in detail.

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #1314520` if this solves the issue #15213

- [ ] I have raised an issue to propose this change ([required](https://github.com/PKU-Alignment/align-anything/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/PKU-Alignment/align-anything/blob/HEAD/.github/CONTRIBUTING.md) guide. (**required**)
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: projects/ti_to_ti/preference_tokenize_example.py
[the remark this answers is not in the document]
Comment (cby-pku) [reply projects/ti_to_ti/preference_tokenize_example.py:1]: ## Q5: Minor problems.
1. I also met Q2 when use `python pre_tokenize_parallel_example.py`.

[the remark this answers is not in the document]
Comment (cby-pku) [reply projects/ti_to_ti/preference_tokenize_example.py:1]: ## Q6: About Pre-tokenization.

I am not familiar with `pre-tokenization`, but I noticed that in this pr, during pre-tokenization, `input_image` and `output_image` are set to `None` in `format_sample_spavl` method, but `better_text` and `worse_text` are set to `None` in `format_sample_pickapic` method.

Reference:
```
def format_sample_pickapic(raw_sample: dict[str, Any]) -> dict[str, Any]:
    prompt = f"Generate an image according to the following prompt: {raw_sample['caption']}"
    better_id = int(raw_sample['label_1'])
    worse_id = int(raw_sample['label_0'])

    raw_better_image = raw_sample[f'jpg_{better_id}']
    raw_worse_image = raw_sample[f'jpg_{worse_id}']
    better_image = Image.open(io.BytesIO(raw_better_image)).convert('RGB')
    worse_image = Image.open(io.BytesIO(raw_worse_image)).convert('RGB')
    raw_sample = {
        "input_text": prompt,
        "input_image": [],
        "better_text": "",
        "better_img": better_image,
        "worse_text": "",
        "worse_img": worse_image
    }
    return format_sample_cham(raw_sample)

def format_sample_spavl(raw_sample: dict[str, Any]) -> dict[str, Any]:
    raw_sample = {
        "input_text": raw_sample['question'],
        "input_image": Image.open(io.BytesIO(raw_sample['image']['bytes'])),
        "better_text": raw_sample['chosen'],
        "better_img": None,
        "worse_text": raw_sample['rejected'],
        "worse_img": None
    }
    return format_sample_cham(raw_sample)
```

[the remark this answers is not in the document]
Comment (cby-pku) [reply projects/ti_to_ti/preference_tokenize_example.py:1]: But, in `pre_tokenize_parrallel_example.py`, in the`format_sample` and `format_sample_cham` method, both text and image is set to specifc value.

[the remark this answers is not in the document]
Comment (cby-pku) [reply projects/ti_to_ti/preference_tokenize_example.py:1]: Why? I am curious about it. Thanks to author's efforts.

**Review by cby-pku — CHANGES_REQUESTED** [review]
Thanks to the author's efforts! There are some comments. Hope for your reply!
These comments are about `pre-tokenization` module, and I will next run the SFT and DPO training part. See you later ~

File: projects/ti_to_ti/README.md [hunk 1]
```diff
@@ -76,6 +88,133 @@ and set up the correct model path and dataset path, then run:
 bash scripts/sft_ti_to_ti.sh
```
Comment (cby-pku) [inline projects/ti_to_ti/README.md:88]: It is vague here. So the `model_name_or_path` here should be the `pt` file which is after the pre-tokenization ?

**Review by cby-pku — COMMENTED** [review]
**Note, I cloned your `dev-cham` branch in the fork github and test the code. I think it is the branch that you set up the pr.**

File: projects/ti_to_ti/preference_tokenize_example.py [hunk 2]
```diff
@@ -0,0 +1,308 @@
...
+    if list1 is None and list2 is None:
+        return []
+    elif list1 is None:
+        return list2.copy()
+    elif list2 is None:
+        return list1.copy()
+    else:
+        return list1 + list2
+    
+def format_sample_cham(raw_sample: dict[str, Any]) -> dict[str, Any]:
```
[the remark this answers is not in the document]
Comment (htlou) [reply projects/ti_to_ti/preference_tokenize_example.py:94]: Fixed in https://github.com/PKU-Alignment/align-anything/pull/46/commits/71067a935888c0d75b5003674a395464a0b2cfb2 by adding a docstring to every format_sample function. Hope this would make the code easier to read and clarify some misunderstandings.

File: projects/ti_to_ti/preference_tokenize_example.py
[the remark this answers is not in the document]
Comment (htlou) [reply projects/ti_to_ti/preference_tokenize_example.py:1]: OK I will deal with them one by one.

## Q1

Solved in https://github.com/PKU-Alignment/align-anything/pull/46/commits/71067a935888c0d75b5003674a395464a0b2cfb2 by adding a docstring to each format_sample function.

## Q2

As I checked both environments, it is a problem caused by nvcc version, which will raise an error is nvcc is in 12.5 but works well in nvcc 12.1. Luckily your fix won't affect the run in nvcc 12.1, so I add it into my code in https://github.com/PKU-Alignment/align-anything/pull/46/commits/0e3936cd7e110f2622c9b294761e3eb9c50f533d.

## Q3

Solved in https://github.com/PKU-Alignment/align-anything/pull/46/commits/0e3936cd7e110f2622c9b294761e3eb9c50f533d and https://github.com/PKU-Alignment/align-anything/pull/46/commits/8dc36e642fd31b75b0d76647da6459cda211ef13. I change all the load method back to json file and provide all the changes needed if some users want to switch to load_dataset.

## Q5

Solved in `Q2`.

## Q6

This is because you are using the prompt_only pre-tokenization, which is designed for PPO (just like the prompt_only python file in datasets), in which only prompt and input image are needed, therefore actually only input_text and input_image are needed. I changed all the functions in the prompt_only_tokenize_example.py and deleted unnecessary lines in https://github.com/PKU-Alignment/align-anything/pull/46/commits/cb94ee9de9e6e5423b340046d317caf05830db95.

File: align_anything/datasets/ti_to_ti/supervised.py
Comment (cby-pku) [inline align_anything/datasets/ti_to_ti/supervised.py:1]: ## Q2 About the DatasetLoader

When I run sft_ti2ti, it occurs the following error.

Error Information below:
```
[rank3]: TypeError: SupervisedTokenizedDataset.__init__() got an unexpected keyword argument 'name'
[rank6]: Traceback (most recent call last):
[rank6]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank6]:   File "<frozen runpy>", line 88, in _run_code
[rank6]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/sft.py", line 92, in <module>
[rank6]:     sys.exit(main())
[rank6]:              ^^^^^^
[rank6]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/sft.py", line 86, in main
[rank6]:     trainer = SuperviseTrainer(cfgs=cfgs, ds_cfgs=ds_cfgs)
[rank6]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/text_to_text/sft.py", line 56, in __init__
[rank6]:     self.init_datasets()
[rank6]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/sft.py", line 43, in init_datasets
[rank6]:     self.train_dataloader, self.eval_dataloader = self.get_dataloaders(
[rank6]:                                                   ^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/base/supervised_trainer.py", line 72, in get_dataloaders
[rank6]:     train_dataset = train_data_dtype(
[rank6]:                     ^^^^^^^^^^^^^^^^^
[rank6]: TypeError: SupervisedTokenizedDataset.__init__() got an unexpected keyword argument 'name'
[rank2]: Traceback (most recent call last):
[rank2]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank2]:   File "<frozen runpy>", line 88, in _run_code
[rank2]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/sft.py", line 92, in <module>
[rank2]:     sys.exit(main())
[rank2]:              ^^^^^^
[rank2]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/sft.py", line 86, in main
[rank2]:     trainer = SuperviseTrainer(cfgs=cfgs, ds_cfgs=ds_cfgs)
[rank2]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/text_to_text/sft.py", line 56, in __init__
[rank2]:     self.init_datasets()
[rank2]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/sft.py", line 43, in init_datasets
[rank2]:     self.train_dataloader, self.eval_dataloader = self.get_dataloaders(
[rank2]:                                                   ^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/base/supervised_trainer.py", line 72, in get_dataloaders
[rank2]:     train_dataset = train_data_dtype(
[rank2]:                     ^^^^^^^^^^^^^^^^^
[rank2]: TypeError: SupervisedTokenizedDataset.__init__() got an unexpected keyword argument 'name'
```

After checking the related python files, it may be the following reason:

```
# datasets/ti_to_ti/supervised.py
class SupervisedTokenizedDataset(Dataset):

    def __init__(
        self,
        path: str,
        template: str | None = None,
        tokenizer: transformers.PreTrainedTokenizer | None = None,
        processor: transformers.ProcessorMixin | transforms.Compose | None = None,
        size: int | None = None,
        split: str | None = None,
        subset: str | None = None,
        data_files: str | None = None,
        optional_args: list | str = [],
    ):

```

But in the `trainers/base/supervised_trainer.py` and `Class SupervisedTrainerBase`

```
    def get_dataloaders(self, train_data_dtype, eval_data_dtype) -> None:
        """Get the dataloaders based on data_dtype."""
        self.train_template = get_template_class(self.cfgs.data_cfgs.train_template)
        train_dataset = train_data_dtype(
            path=self.cfgs.data_cfgs.train_datasets,
            template=self.cfgs.data_cfgs.train_template,
            tokenizer=self.tokenizer,
            processor=self.processor,
            name=self.cfgs.data_cfgs.train_name,
            size=self.cfgs.data_cfgs.train_size,
            split=self.cfgs.data_cfgs.train_split,
            subset=self.cfgs.data_cfgs.train_subset,
            data_files=self.cfgs.data_cfgs.train_data_files,
            optional_args=self.cfgs.data_cfgs.train_optional_args,
        )
```
the `get_dataloaders` methods need to pass the `name` key, which is not defined in the `Class SupervisedTokenizedDataset`.

File: align_anything/configs/template.py [hunk 3]
```diff
@@ -252,6 +280,193 @@ def format_sample(self, raw_sample: dict[str, Any], path: str=None) -> dict[str,
...
+        
+@register_template('AA_textfeedback')
+class AA_TF:
+    system_prompt: str = 'BEGINNING OF CONVERSATION: '
+    user_prompt: str = 'USER: Judge the following two response of the same question and give a preference: \n ##Question: {input} \n ##Response 1: {response_1} \n ##Response 2: {response_2}'
+    assistant_prompt: str = '\nASSISTANT:{output}'
+    split_token: str = 'ASSISTANT:'
+    separator: str = '###'
+    
+    def format_sample(self, raw_sample: dict[str, Any], path: Optional) -> dict[str, Any]:
```
[the remark this answers is not in the document]
Comment (htlou) [reply align_anything/configs/template.py:350]: fixed in https://github.com/PKU-Alignment/align-anything/pull/46/commits/8aebcb75d0dc12cf903fd1387357f7e0013c1693

File: projects/ti_to_ti/README.md (hunk 1 above)
Comment (htlou) [reply projects/ti_to_ti/README.md:88]: Fixed in https://github.com/PKU-Alignment/align-anything/pull/46/commits/9b65944e86268263ef27c38e063a06a264cdf74b, I claimed in all the scripts what the arguments should look like

**Comment by htlou** [comment]
Fixed all the requests and comments in the commits above.

**Review by cby-pku — CHANGES_REQUESTED** [review]
Some Comments about `sft_ti2ti` training

File: projects/ti_to_ti/preference_tokenize_example.py
[the remark this answers is not in the document]
Comment (cby-pku) [reply projects/ti_to_ti/preference_tokenize_example.py:1]: Thanks a lot! But about Q6, actually, I reference to preference_tokenize_example.py

[the remark this answers is not in the document]
Comment (cby-pku) [reply projects/ti_to_ti/preference_tokenize_example.py:1]: Oh, I fixed it. Thanks your reply.

File: align_anything/datasets/ti_to_ti/supervised.py
Comment (htlou) [reply align_anything/datasets/ti_to_ti/supervised.py:1]: Fixed in https://github.com/PKU-Alignment/align-anything/pull/46/commits/ed9ca9a314ff6cbce906b245f1acde67a3475084, where I add a name parameter in all three files under ti_to_ti

Comment (htlou) [reply align_anything/datasets/ti_to_ti/supervised.py:1]: Fixed in https://github.com/PKU-Alignment/align-anything/pull/46/commits/5a67acf7fc7905f9fa998c0b3ae34beaeaf31cdf, where I deleted all hostfile related stuff.

**Review by cby-pku — COMMENTED** [review]
Remember to have a more clear claim about `TRAIN_DATASETS` and `FILE_NAME` in the bash scripts and README.md

**Review by cby-pku — COMMENTED** [review]
Moreover, change in the README: name of `preference_tokenize_example.py`

File: align_anything/configs/template.py
Comment (cby-pku) [inline align_anything/configs/template.py:1]:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/dpo.py", line 104, in <module>
[rank0]:     sys.exit(main())
[rank0]:              ^^^^^^
[rank0]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/dpo.py", line 98, in main
[rank0]:     trainer = DPOTrainer(cfgs=cfgs, ds_cfgs=ds_cfgs)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/text_to_text/dpo.py", line 64, in __init__
[rank0]:     self.init_datasets()
[rank0]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/ti_to_ti/dpo.py", line 46, in init_datasets
[rank0]:     self.train_dataloader, self.eval_dataloader = self.get_dataloaders(
[rank0]:                                                   ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/trainers/base/supervised_trainer.py", line 72, in get_dataloaders
[rank0]:     train_dataset = train_data_dtype(
[rank0]:                     ^^^^^^^^^^^^^^^^^
[rank0]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/datasets/ti_to_ti/preference.py", line 156, in __init__
[rank0]:     self.valid_indices = self.fillter_indices()
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/aifs4su/yaodong/boyuan/workspace/align-anything/align_anything/datasets/ti_to_ti/preference.py", line 163, in fillter_indices
[rank0]:     if not self.template.check_equal(item):
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: AttributeError: 'ANYTHING_TI2TI' object has no attribute 'check_equal'
```

Remember to add `check_equal` method:
```
    def check_equal(self, raw_sample: dict[str, Any]) -> bool:
        return torch.equal(raw_sample['better_input_ids'], raw_sample['worse_input_ids'])
```

**Review by cby-pku — CHANGES_REQUESTED** [review]
Question about DPO

File: align_anything/configs/template.py
Comment (htlou) [reply align_anything/configs/template.py:1]: Fixed in https://github.com/PKU-Alignment/align-anything/pull/46/commits/f81ed0bbcc923f6cd00eb2b4c467902c20392308

**Comment by htlou** [comment]
Modified my commit according to @cby-pku's advice and requests. Therefore, I request another round of review

File: align_anything/trainers/ti_to_ti/dpo.py
Comment (XuyaoWang) [inline align_anything/trainers/ti_to_ti/dpo.py:1]: 1. check if all parameters are frozen
2. check if set model.eval()

File: align_anything/trainers/ti_to_ti/ppo.py
Comment (XuyaoWang) [inline align_anything/trainers/ti_to_ti/ppo.py:1]: delete `print` from line 131

Comment (htlou) [reply align_anything/trainers/ti_to_ti/ppo.py:1]: Fixed in https://github.com/PKU-Alignment/align-anything/pull/46/commits/5b8130dbba86fcadbbdc1b58601e5f8c7d3b65f1

File: align_anything/trainers/ti_to_ti/dpo.py
Comment (htlou) [reply align_anything/trainers/ti_to_ti/dpo.py:1]: This should be a check on its parent class rather than this file itself, as I directly inherit most of this trainer from text_to_text DPO trainer

**Review by cby-pku — APPROVED** [review]

**Review by XuyaoWang — APPROVED** [review]
LGTM.
